import {FastifyInstance} from 'fastify';
import {z} from 'zod';
import crypto from 'node:crypto';
import {service} from '../../application/payments/service.js';
import {pool} from '../../infrastructure/db/mysql.js';
import {FinancialOperationsService} from '../../application/financial/service.js';
import {RiskService} from '../../application/risk/service.js';
import {BillingService} from '../../application/billing/service.js';
import {ComplianceService} from '../../application/compliance/service.js';
import {ReportsService} from '../../application/reports/service.js';
import {ProviderCallbackService} from '../../application/payments/provider-callback.js';
import {LedgerService} from '../../application/ledger/service.js';
import {ZohoBooksService} from '../../infrastructure/integrations/zoho-books.js';
import {redisPing} from '../../infrastructure/db/redis.js';
import {encryptProviderToken,decryptProviderToken} from '../../application/payments/token-vault.js';
import {hashPassword,verifyPassword,hashToken,randomToken,securityEvent} from '../../security.js';
import {emitOutbox} from '../../application/integrations.js';
import {upsertRegionalPolicy,supportedRegions} from '../../application/regional.js';
import {config} from '../../config.js';

const hash=(v:string)=>crypto.createHash('sha256').update(v).digest('hex');
const fail=(code:string,statusCode:number)=>Object.assign(new Error(code),{statusCode,code});
const response=(r:any,data:any)=>({data,request_id:r.id});
function paging(q:any){const limit=Math.min(Math.max(Number(q?.limit||50),1),100);const offset=Math.max(Number(q?.offset||0),0);return {limit,offset};}
function moneyFilter(q:any){const parts:string[]=[];const args:any[]=[];if(q?.status){parts.push('status=?');args.push(String(q.status).toUpperCase());}if(q?.currency){parts.push('currency=?');args.push(String(q.currency).toUpperCase());}return {sql:parts.length?` AND ${parts.join(' AND ')}`:'',args};}

async function auth(r:any){
 const value=String(r.headers.authorization||'');
 if(value.startsWith('Bearer ')){
  const raw=value.slice(7).trim(); const [rows]:any=await pool.query(`SELECT s.*,u.email,u.name,u.status,u.mfa_enabled FROM user_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>CURRENT_TIMESTAMP(6) AND u.status='ACTIVE'`,[hashToken(raw)]);
  if(!rows[0]) throw fail('INVALID_SESSION',401);
  return {tenantId:rows[0].tenant_id,merchantId:null,userId:rows[0].user_id,sessionId:rows[0].id,keyId:null,permissions:null};
 }
 if(value.startsWith('Api-Key ')){
  const raw=value.slice(8).trim();
  const [rows]:any=await pool.query('SELECT * FROM api_keys WHERE secret_hash=? AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at>CURRENT_TIMESTAMP(6))',[hash(raw)]);
  if(!rows[0]) throw fail('INVALID_API_KEY',401);
  await pool.query('UPDATE api_keys SET last_used_at=CURRENT_TIMESTAMP(6) WHERE id=?',[rows[0].id]);
  return {tenantId:rows[0].tenant_id,merchantId:rows[0].merchant_id||null,userId:null,keyId:rows[0].id,permissions:rows[0].scopes_json?JSON.parse(rows[0].scopes_json):null};
 }
 if(config.isProduction) throw fail('AUTHENTICATION_REQUIRED',401);
 const t=String(r.headers['x-tenant-id']||'550e8400-e29b-41d4-a716-446655440000');
 return {tenantId:t,merchantId:null,userId:null,sessionId:null,keyId:null,permissions:null};
}
async function requirePermission(r:any,code:string){
 if(!r.auth) throw fail('AUTHENTICATION_REQUIRED',401);
 if(!r.auth.userId) { if(r.auth.permissions && !r.auth.permissions.includes('*') && !r.auth.permissions.includes(code)) throw fail('FORBIDDEN',403); return; }
 const [rows]:any=await pool.query(`SELECT 1 FROM user_roles ur JOIN role_permissions rp ON rp.role_id=ur.role_id JOIN permissions p ON p.id=rp.permission_id WHERE ur.user_id=? AND p.code=? LIMIT 1`,[r.auth.userId,code]);
 if(!rows[0]) throw fail('FORBIDDEN',403);
}
function totp(secret:string,code:string){const alpha='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const ch of secret.replace(/=+$/,'')){const n=alpha.indexOf(ch);if(n<0)return false;bits+=n.toString(2).padStart(5,'0');}const buf=Buffer.alloc(Math.floor(bits.length/8));for(let i=0;i<buf.length;i++)buf[i]=parseInt(bits.slice(i*8,i*8+8),2);const counter=Math.floor(Date.now()/1000/30);return [counter-1,counter,counter+1].some(c=>{const msg=Buffer.alloc(8);msg.writeBigUInt64BE(BigInt(c));const h=crypto.createHmac('sha1',buf).update(msg).digest();const off=h[19]&15;const otp=((h[off]&127)<<24)|(h[off+1]<<16)|(h[off+2]<<8)|h[off+3];return String(otp%1000000).padStart(6,'0')===code;});}
async function createSession(user:any,r:any){const raw=randomToken(32);const ttlHours=Math.min(Math.max(Math.trunc(Number(config.sessionTtlHours)||24),1),720);const sql=`INSERT INTO user_sessions(id,tenant_id,user_id,token_hash,expires_at,ip,user_agent) VALUES(?,?,?,?,DATE_ADD(CURRENT_TIMESTAMP(6),INTERVAL ${ttlHours} HOUR),?,?)`;await pool.query(sql,[crypto.randomUUID(),user.tenant_id,user.id,hashToken(raw),r.ip,String(r.headers['user-agent']||'')]);return raw;}
const financial=new FinancialOperationsService();
const risk=new RiskService();
const billing=new BillingService();
const compliance=new ComplianceService();
const reports=new ReportsService();
const providerCallbacks=new ProviderCallbackService(new LedgerService());
const zohoBooks=new ZohoBooksService();
const idem=(r:any)=>{const k=r.headers['idempotency-key'];if(!k||Array.isArray(k)) throw fail('IDEMPOTENCY_KEY_REQUIRED',400);return k;};

export async function routes(app:FastifyInstance){
 app.addHook('preHandler',async(r:any)=>{if(r.url==='/health'||r.url==='/health/ready'||r.url==='/v1/auth/login'||r.url==='/v1/auth/mfa/verify'||r.url.startsWith('/checkout/public/')||r.url.startsWith('/pay/')||r.url==='/v1/integrations/zoho-books/oauth/callback'||r.url==='/v1/webhooks/provider/paytabs') return;r.auth=await auth(r);});
 app.get('/health',async()=>({status:'ok',service:'payment-platform-api',version:'3.4.0'}));
 app.get('/health/ready',async(_r,reply)=>{let db='ok',redis:'ok'|'disabled'|'error'='disabled';try{await pool.query('SELECT 1')}catch{db='error'};try{redis=await redisPing()}catch{redis='error'};const ready=db==='ok'&&(!process.env.REDIS_URL||redis==='ok');return reply.code(ready?200:503).send({status:ready?'ready':'not_ready',checks:{database:db,redis}});});
 app.post('/v1/auth/login',async(r:any,reply:any)=>{
  const v=z.object({tenant_id:z.string().uuid(),email:z.string().email(),password:z.string().min(8)}).parse(r.body);
  const [rows]:any=await pool.query('SELECT * FROM users WHERE tenant_id=? AND email=? LIMIT 1',[v.tenant_id,v.email]); const u=rows[0];
  if(!u){await securityEvent({tenantId:v.tenant_id,eventType:'login.failed',success:false,ip:r.ip,userAgent:String(r.headers['user-agent']||''),metadata:{reason:'unknown_user'}});throw fail('INVALID_CREDENTIALS',401);}
  if(u.locked_until&&new Date(u.locked_until).getTime()>Date.now()) throw fail('ACCOUNT_LOCKED',423);
  if(!u.password_hash||!verifyPassword(v.password,u.password_hash)){const attempts=Number(u.failed_login_attempts||0)+1;const locked=attempts>=config.loginMaxAttempts?new Date(Date.now()+config.loginLockMinutes*60000):null;await pool.query('UPDATE users SET failed_login_attempts=?,locked_until=? WHERE id=?',[locked?0:attempts,locked,u.id]);await securityEvent({tenantId:u.tenant_id,userId:u.id,eventType:'login.failed',success:false,ip:r.ip,userAgent:String(r.headers['user-agent']||''),metadata:{attempts}});throw fail('INVALID_CREDENTIALS',401);}
  await pool.query('UPDATE users SET failed_login_attempts=0,locked_until=NULL,last_login_at=CURRENT_TIMESTAMP(6),last_login_ip=? WHERE id=?',[r.ip,u.id]);
  if(u.mfa_enabled){const challenge=randomToken(24);await pool.query('INSERT INTO mfa_challenges(id,tenant_id,user_id,challenge_hash,expires_at) VALUES(?,?,?,?,DATE_ADD(CURRENT_TIMESTAMP(6),INTERVAL 5 MINUTE))',[crypto.randomUUID(),u.tenant_id,u.id,hashToken(challenge)]);return {mfa_required:true,challenge};}
  const token=await createSession(u,r);await securityEvent({tenantId:u.tenant_id,userId:u.id,eventType:'login.succeeded',ip:r.ip,userAgent:String(r.headers['user-agent']||'')});return {access_token:token,token_type:'Bearer',expires_in:config.sessionTtlHours*3600,user:{id:u.id,email:u.email,name:u.name,tenant_id:u.tenant_id}};
 });
 app.post('/v1/auth/mfa/verify',async(r:any)=>{const v=z.object({tenant_id:z.string().uuid(),challenge:z.string().min(20),code:z.string().regex(/^\d{6}$/)}).parse(r.body);const [rows]:any=await pool.query('SELECT c.*,u.* FROM mfa_challenges c JOIN users u ON u.id=c.user_id WHERE c.tenant_id=? AND c.challenge_hash=? AND c.used_at IS NULL AND c.expires_at>CURRENT_TIMESTAMP(6)',[v.tenant_id,hashToken(v.challenge)]);if(!rows[0])throw fail('INVALID_MFA_CHALLENGE',401);const secret=decryptProviderToken(rows[0].mfa_secret_encrypted);if(!totp(secret,v.code))throw fail('INVALID_MFA_CODE',401);await pool.query('UPDATE mfa_challenges SET used_at=CURRENT_TIMESTAMP(6) WHERE id=?',[rows[0].id]);const token=await createSession(rows[0],r);await securityEvent({tenantId:rows[0].tenant_id,userId:rows[0].user_id,eventType:'mfa.login.succeeded',ip:r.ip,userAgent:String(r.headers['user-agent']||'')});return {access_token:token,token_type:'Bearer',expires_in:config.sessionTtlHours*3600,user:{id:rows[0].user_id,email:rows[0].email,name:rows[0].name,tenant_id:rows[0].tenant_id}};});
 app.post('/v1/auth/logout',async(r:any)=>{if(r.auth?.sessionId)await pool.query('UPDATE user_sessions SET revoked_at=CURRENT_TIMESTAMP(6) WHERE id=?',[r.auth.sessionId]);return {ok:true};});
 app.get('/v1/auth/me',async(r:any)=>{if(!r.auth?.userId) return response(r,{authenticated:true,mode:r.auth?.keyId?'api_key':'development',tenant_id:r.auth?.tenantId});const [rows]:any=await pool.query('SELECT id,email,name,status,mfa_enabled,tenant_id FROM users WHERE id=?',[r.auth.userId]);if(!rows[0])throw fail('INVALID_SESSION',401);const [merchants]:any=await pool.query('SELECT id FROM merchants WHERE tenant_id=? AND status=\'ACTIVE\' ORDER BY created_at ASC LIMIT 1',[rows[0].tenant_id]);return response(r,{...rows[0],merchant_id:merchants[0]?.id||null});});


 app.get('/v1/dashboard/summary',async(r:any)=>{const t=r.auth.tenantId;const [[p]]:any=await pool.query("SELECT COUNT(*) total,SUM(status='SUCCEEDED') successful,SUM(status='FAILED') failed,COALESCE(SUM(CASE WHEN status='SUCCEEDED' THEN amount_minor ELSE 0 END),0) volume_minor FROM payments WHERE tenant_id=?",[t]);const [[ref]]:any=await pool.query("SELECT COUNT(*) refunds,COALESCE(SUM(amount_minor),0) amount_minor FROM refunds WHERE tenant_id=? AND status='SUCCESS'",[t]);const [[bal]]:any=await pool.query("SELECT COALESCE(SUM(ab.available_minor),0) available_minor,COALESCE(SUM(ab.pending_minor),0) pending_minor,COALESCE(SUM(ab.reserve_minor),0) reserve_minor FROM account_balances ab JOIN ledger_accounts la ON la.id=ab.account_id WHERE la.tenant_id=? AND la.type='LIABILITY' AND la.code LIKE 'merchant_payable:%'",[t]);return response(r,{payments:{total:Number(p.total||0),successful:Number(p.successful||0),failed:Number(p.failed||0),volume_minor:String(p.volume_minor||0)},refunds:{count:Number(ref.refunds||0),amount_minor:String(ref.amount_minor||0)},balances:{available_minor:String(bal.available_minor||0),pending_minor:String(bal.pending_minor||0),reserve_minor:String(bal.reserve_minor||0)}});});

 app.get('/v1/customers',async(r:any)=>{const {limit,offset}=paging(r.query);const q=(r.query as any)?.search;const args:any[]=[r.auth.tenantId];let where='tenant_id=?';if(q){where+=' AND (name LIKE ? OR email LIKE ? OR phone LIKE ?)';const s=`%${q}%`;args.push(s,s,s);}const [rows]:any=await pool.query(`SELECT * FROM customers WHERE ${where} ORDER BY created_at DESC LIMIT ? OFFSET ?`,[...args,limit,offset]);return response(r,rows);});
 app.post('/v1/customers',async(r:any,reply:any)=>{const v=z.object({merchant_id:z.string().uuid(),name:z.string().min(1).max(255),email:z.string().email().optional(),phone:z.string().max(64).optional()}).parse(r.body);const id=crypto.randomUUID();const [m]:any=await pool.query('SELECT id FROM merchants WHERE id=? AND tenant_id=?',[v.merchant_id,r.auth.tenantId]);if(!m[0])throw fail('MERCHANT_NOT_FOUND',404);await pool.query('INSERT INTO customers(id,tenant_id,merchant_id,name,email,phone,status) VALUES(?,?,?,?,?,?,?)',[id,r.auth.tenantId,v.merchant_id,v.name,v.email||null,v.phone||null,'ACTIVE']);return reply.code(201).send(response(r,{id,...v,status:'ACTIVE'}));});
 app.get('/v1/customers/:id',async(r:any)=>{const [rows]:any=await pool.query('SELECT * FROM customers WHERE id=? AND tenant_id=?',[r.params.id,r.auth.tenantId]);if(!rows[0])throw fail('CUSTOMER_NOT_FOUND',404);return response(r,rows[0]);});
 app.get('/v1/customers/:customerId/payment-methods',async(r:any)=>response(r,await service.listPaymentMethods(r.params.customerId,r.auth.tenantId)));

 app.get('/v1/payment-methods',async(r:any)=>{const [rows]:any=await pool.query('SELECT id,merchant_id,customer_id,type,brand,last4,exp_month,exp_year,status,created_at FROM payment_methods WHERE tenant_id=? ORDER BY created_at DESC LIMIT 100',[r.auth.tenantId]);return response(r,rows);});
 app.post('/v1/payment-method-sessions',async(r:any,reply:any)=>{const v=z.object({merchant_id:z.string().uuid(),customer_id:z.string().uuid(),type:z.string().default('CARD')}).parse(r.body);return reply.code(201).send(response(r,await service.createPaymentMethodSession(v,r.auth.tenantId)));});
 app.post('/v1/payment-methods',async(r:any,reply:any)=>{const v=z.object({merchant_id:z.string().uuid(),customer_id:z.string().uuid(),type:z.enum(['CARD','BANK_ACCOUNT','BANK_TRANSFER','ACH','UPI','WALLET','REGIONAL_METHOD','PROVIDER_METHOD']),provider_token:z.string().min(3),brand:z.string().optional(),last4:z.string().length(4).optional(),exp_month:z.number().int().min(1).max(12).optional(),exp_year:z.number().int().optional()}).parse(r.body);return reply.code(201).send(response(r,await service.createPaymentMethod(v,r.auth.tenantId)));});

 app.post('/v1/payment-sessions',async(r:any,reply:any)=>{const v=z.object({merchant_id:z.string().uuid(),customer_id:z.string().uuid().nullable().optional(),amount_minor:z.union([z.string(),z.number().int().positive()]),currency:z.string().length(3).transform((v:string)=>v.toUpperCase()),reference:z.string().max(255).optional(),description:z.string().optional(),return_url:z.string().url().optional(),cancel_url:z.string().url().optional(),expires_at:z.string().datetime().optional()}).parse(r.body);return reply.code(201).send(response(r,await service.createSession(v,r.auth.tenantId,idem(r))));});
 app.get('/v1/payment-sessions/:id',async(r:any)=>response(r,await service.getSession(r.params.id,r.auth.tenantId)));
 app.post('/v1/payment-sessions/:id/pay',async(r:any)=>response(r,await service.pay(r.params.id,r.auth.tenantId,(r.body as any)?.payment_method_id,idem(r),(r.body as any)?.payment_method_token)));
 app.post('/v1/payment-method-sessions/:id/confirm',async(r:any)=>{const v=z.object({client_secret:z.string().min(10),provider_token:z.string().min(3)}).parse(r.body);return response(r,await service.confirmPaymentMethodSession(r.params.id,v.client_secret,v.provider_token,r.auth.tenantId));});

 app.get('/v1/payments',async(r:any)=>{await requirePermission(r,'payments.read');const {limit,offset}=paging(r.query);const f=moneyFilter(r.query);const search=String((r.query as any)?.search||'');let extra=f.sql;const args:any[]=[r.auth.tenantId,...f.args];if(search){extra+=' AND (id=? OR reference LIKE ? OR provider_transaction_id LIKE ?)';args.push(search,`%${search}%`,`%${search}%`);}const [rows]:any=await pool.query(`SELECT * FROM payments WHERE tenant_id=?${extra} ORDER BY created_at DESC LIMIT ? OFFSET ?`,[...args,limit,offset]);return response(r,rows);});
 app.get('/v1/payments/:id',async(r:any)=>response(r,await service.getPaymentDetails(r.params.id,r.auth.tenantId)));
 app.post('/v1/payments/:id/refunds',async(r:any,reply:any)=>{await requirePermission(r,'payments.refund');const v=z.object({amount_minor:z.union([z.string(),z.number().int().positive()]),reason:z.string().max(255).optional()}).parse(r.body);return reply.code(201).send(response(r,await service.refund(r.params.id,v,r.auth.tenantId,idem(r))));});
 app.get('/v1/payments/:id/refunds',async(r:any)=>{const [rows]:any=await pool.query('SELECT * FROM refunds WHERE payment_id=? AND tenant_id=? ORDER BY created_at DESC',[r.params.id,r.auth.tenantId]);return response(r,rows);});
 app.get('/v1/refunds',async(r:any)=>{const {limit,offset}=paging(r.query);const [rows]:any=await pool.query('SELECT r.*,p.reference,p.customer_id FROM refunds r JOIN payments p ON p.id=r.payment_id WHERE r.tenant_id=? ORDER BY r.created_at DESC LIMIT ? OFFSET ?',[r.auth.tenantId,limit,offset]);return response(r,rows);});

 app.get('/v1/balance',async(r:any)=>{const currency=String((r.query as any)?.currency||'USD').toUpperCase();const [rows]:any=await pool.query("SELECT id AS merchant_id FROM merchants WHERE tenant_id=? ORDER BY created_at LIMIT 1",[r.auth.tenantId]);if(!rows[0])return response(r,{currency,ledger:'0',available:'0',pending:'0',reserve:'0'});return response(r,await service.getBalance(rows[0].merchant_id,r.auth.tenantId,currency));});
 app.get('/v1/balances/:merchantId',async(r:any)=>response(r,await service.getBalance(r.params.merchantId,r.auth.tenantId,String(r.query?.currency||'USD').toUpperCase())));

 app.post('/v1/payment-links',async(r:any,reply:any)=>{const v=z.object({merchant_id:z.string().uuid(),amount_minor:z.union([z.string(),z.number().int().positive()]),currency:z.string().length(3).transform((v:string)=>v.toUpperCase()),reference:z.string().optional(),description:z.string().optional(),customer_email:z.string().email().optional(),customer_phone:z.string().optional(),expires_at:z.string().datetime().optional()}).parse(r.body);return reply.code(201).send(response(r,await service.createPaymentLink(v,r.auth.tenantId)));});
 app.get('/v1/payment-links',async(r:any)=>{const {limit,offset}=paging(r.query);const [rows]:any=await pool.query('SELECT id,merchant_id,amount_minor,currency,reference,description,customer_email,expires_at,status,public_token,created_at FROM payment_links WHERE tenant_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?',[r.auth.tenantId,limit,offset]);return response(r,rows);});
 app.get('/v1/payment-links/:id',async(r:any)=>response(r,await service.getPaymentLink(r.params.id,r.auth.tenantId)));
 app.post('/v1/payment-links/:id/cancel',async(r:any)=>{const [x]:any=await pool.query("UPDATE payment_links SET status='CANCELLED' WHERE id=? AND tenant_id=? AND status='ACTIVE'",[r.params.id,r.auth.tenantId]);if(!x.affectedRows)throw fail('PAYMENT_LINK_NOT_CANCELLABLE',409);return response(r,{id:r.params.id,status:'CANCELLED'});});
 app.post('/v1/payment-links/:id/pay',async(r:any)=>response(r,await service.payLink(r.params.id,r.auth.tenantId,idem(r))));

 app.get('/checkout/public/:token',async(r:any)=>response(r,await service.getPublicPaymentLink(r.params.token)));
 app.post('/checkout/public/:token/pay',async(r:any)=>response(r,await service.payPublicPaymentLink(r.params.token,idem(r),(r.body as any)?.payment_method_token)));

 app.post('/v1/api-keys',async(r:any,reply:any)=>{const v=z.object({name:z.string().min(1).max(255),merchant_id:z.string().uuid().optional(),expires_at:z.string().datetime().optional()}).parse(r.body);if(v.merchant_id){const [m]:any=await pool.query('SELECT id FROM merchants WHERE id=? AND tenant_id=?',[v.merchant_id,r.auth.tenantId]);if(!m[0])throw fail('MERCHANT_NOT_FOUND',404);}const id=crypto.randomUUID();const secret='pk_test_'+crypto.randomBytes(24).toString('base64url');await pool.query('INSERT INTO api_keys(id,tenant_id,merchant_id,name,key_prefix,secret_hash,expires_at) VALUES(?,?,?,?,?,?,?)',[id,r.auth.tenantId,v.merchant_id||null,v.name,secret.slice(0,16),hash(secret),v.expires_at?new Date(v.expires_at):null]);return reply.code(201).send(response(r,{id,name:v.name,key_prefix:secret.slice(0,16),secret,warning:'Store this secret now. It will not be shown again.'}));});
 app.get('/v1/api-keys',async(r:any)=>{const [rows]:any=await pool.query('SELECT id,name,key_prefix,merchant_id,last_used_at,expires_at,revoked_at,created_at FROM api_keys WHERE tenant_id=? ORDER BY created_at DESC',[r.auth.tenantId]);return response(r,rows);});
 app.post('/v1/api-keys/:id/revoke',async(r:any)=>{const [x]:any=await pool.query('UPDATE api_keys SET revoked_at=CURRENT_TIMESTAMP(6) WHERE id=? AND tenant_id=? AND revoked_at IS NULL',[r.params.id,r.auth.tenantId]);if(!x.affectedRows)throw fail('API_KEY_NOT_FOUND',404);return response(r,{id:r.params.id,status:'REVOKED'});});

 app.get('/v1/audit-logs',async(r:any)=>{const {limit,offset}=paging(r.query);const [rows]:any=await pool.query('SELECT * FROM audit_logs WHERE tenant_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?',[r.auth.tenantId,limit,offset]);return response(r,rows);});
 app.get('/v1/error-reports',async(r:any)=>{await requirePermission(r,'settings.manage');const {limit,offset}=paging(r.query);const [rows]:any=await pool.query('SELECT id,request_id,method,route,status_code,error_code,message,ip,user_agent,query_json,params_json,body_json,headers_json,stack,created_at FROM error_reports WHERE tenant_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?',[r.auth.tenantId,limit,offset]);return response(r,rows);});

 app.get('/v1/webhooks/events',async(r:any)=>{const [rows]:any=await pool.query('SELECT id,event_type,aggregate_type,aggregate_id,payload_json,status,created_at FROM outbox_events WHERE tenant_id=? ORDER BY created_at DESC LIMIT 100',[r.auth.tenantId]);return response(r,rows);});
 app.get('/v1/webhook-deliveries',async(r:any)=>{const {limit,offset}=paging(r.query);const [rows]:any=await pool.query('SELECT d.id,d.endpoint_id,d.event_id,d.attempt,d.status,d.response_code,d.next_retry_at,d.delivered_at,d.created_at,e.event_type,e.aggregate_type,e.aggregate_id,w.url FROM webhook_deliveries d JOIN outbox_events e ON e.id=d.event_id JOIN webhook_endpoints w ON w.id=d.endpoint_id WHERE d.tenant_id=? ORDER BY d.created_at DESC LIMIT ? OFFSET ?',[r.auth.tenantId,limit,offset]);return response(r,rows);});
 app.post('/v1/webhook-deliveries/:id/retry',async(r:any)=>{const [x]:any=await pool.query("UPDATE webhook_deliveries d JOIN webhook_endpoints w ON w.id=d.endpoint_id SET d.status='PENDING',d.next_retry_at=CURRENT_TIMESTAMP(6) WHERE d.id=? AND d.tenant_id=? AND d.status IN ('FAILED','RETRYING')",[r.params.id,r.auth.tenantId]);if(!x.affectedRows)throw fail('WEBHOOK_DELIVERY_NOT_RETRYABLE',409);return response(r,{id:r.params.id,status:'PENDING'});});

 app.post('/v1/webhook-endpoints',async(r:any,reply:any)=>{const v=z.object({url:z.string().url(),events:z.array(z.string()).min(1)}).parse(r.body);const id=crypto.randomUUID(),secret=crypto.randomBytes(32).toString('hex');await pool.query('INSERT INTO webhook_endpoints(id,tenant_id,url,secret,subscribed_events) VALUES(?,?,?,?,?)',[id,r.auth.tenantId,v.url,secret,JSON.stringify(v.events)]);return reply.code(201).send(response(r,{id,url:v.url,secret,status:'ACTIVE',events:v.events}));});
 app.get('/v1/webhook-endpoints',async(r:any)=>{const [rows]:any=await pool.query('SELECT id,url,status,subscribed_events,created_at FROM webhook_endpoints WHERE tenant_id=? ORDER BY created_at DESC',[r.auth.tenantId]);return response(r,rows);});


 // Merchant analytics, financial operations and reporting
 app.get('/v1/dashboard/analytics',async(r:any)=>{const t=r.auth.tenantId;const days=Math.min(Math.max(Number((r.query as any)?.days||30),1),365);const [[m]]:any=await pool.query(`SELECT COUNT(*) total,COALESCE(SUM(amount_minor),0) gross,COALESCE(SUM(fee_minor),0) fees,COALESCE(SUM(CASE WHEN status='SUCCEEDED' THEN 1 ELSE 0 END),0) successful,COALESCE(SUM(CASE WHEN status='FAILED' THEN 1 ELSE 0 END),0) failed,COALESCE(SUM(CASE WHEN status='SUCCEEDED' THEN amount_minor ELSE 0 END),0) successful_volume FROM payments WHERE tenant_id=? AND created_at>=DATE_SUB(CURRENT_TIMESTAMP(6),INTERVAL ${days} DAY)`,[t]);const [[rf]]:any=await pool.query(`SELECT COUNT(*) count,COALESCE(SUM(amount_minor),0) amount FROM refunds WHERE tenant_id=? AND status='SUCCESS' AND created_at>=DATE_SUB(CURRENT_TIMESTAMP(6),INTERVAL ${days} DAY)`,[t]);const [series]:any=await pool.query(`SELECT DATE(created_at) day,COUNT(*) count,COALESCE(SUM(CASE WHEN status='SUCCEEDED' THEN amount_minor ELSE 0 END),0) volume FROM payments WHERE tenant_id=? AND created_at>=DATE_SUB(CURRENT_TIMESTAMP(6),INTERVAL ${days} DAY) GROUP BY DATE(created_at) ORDER BY day`,[t]);return response(r,{days,total:Number(m.total||0),gross_minor:String(m.gross||0),fees_minor:String(m.fees||0),successful:Number(m.successful||0),failed:Number(m.failed||0),success_rate:m.total?Number(m.successful)/Number(m.total):0,successful_volume_minor:String(m.successful_volume||0),refund_count:Number(rf.count||0),refund_minor:String(rf.amount||0),series});});

 app.get('/v1/settlements',async(r:any)=>{const {limit,offset}=paging(r.query);const f=moneyFilter(r.query);const [rows]:any=await pool.query(`SELECT * FROM settlements WHERE tenant_id=?${f.sql} ORDER BY created_at DESC LIMIT ? OFFSET ?`,[r.auth.tenantId,...f.args,limit,offset]);return response(r,rows);});
 app.get('/v1/settlements/:id',async(r:any)=>{const [s]:any=await pool.query('SELECT * FROM settlements WHERE id=? AND tenant_id=?',[r.params.id,r.auth.tenantId]);if(!s[0])throw fail('SETTLEMENT_NOT_FOUND',404);const [items]:any=await pool.query('SELECT si.*,p.reference,p.provider_transaction_id FROM settlement_items si LEFT JOIN payments p ON p.id=si.payment_id WHERE si.settlement_id=? AND si.tenant_id=?',[r.params.id,r.auth.tenantId]);return response(r,{settlement:s[0],items});});
 app.post('/v1/settlements',async(r:any,reply:any)=>{const v=z.object({merchant_id:z.string().uuid(),currency:z.string().length(3).transform((v:string)=>v.toUpperCase()),period_start:z.string(),period_end:z.string()}).parse(r.body);return reply.code(201).send(response(r,await financial.createSettlement(r.auth.tenantId,v.merchant_id,v.currency,v.period_start,v.period_end)));});

 app.get('/v1/payouts',async(r:any)=>{const {limit,offset}=paging(r.query);const [rows]:any=await pool.query('SELECT * FROM payouts WHERE tenant_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?',[r.auth.tenantId,limit,offset]);return response(r,rows);});
 app.get('/v1/payouts/:id',async(r:any)=>{const [p]:any=await pool.query('SELECT * FROM payouts WHERE id=? AND tenant_id=?',[r.params.id,r.auth.tenantId]);if(!p[0])throw fail('PAYOUT_NOT_FOUND',404);const [a]:any=await pool.query('SELECT * FROM payout_attempts WHERE payout_id=? AND tenant_id=? ORDER BY attempt DESC',[r.params.id,r.auth.tenantId]);return response(r,{payout:p[0],attempts:a});});
 app.post('/v1/payouts',async(r:any,reply:any)=>{const v=z.object({merchant_id:z.string().uuid(),bank_account_id:z.string().uuid().optional(),amount_minor:z.union([z.string(),z.number().int().positive()]),currency:z.string().length(3).transform((v:string)=>v.toUpperCase())}).parse(r.body);return reply.code(201).send(response(r,await financial.createPayout(r.auth.tenantId,v.merchant_id,v.bank_account_id,String(v.amount_minor),v.currency)));});

 app.get('/v1/reconciliation/runs',async(r:any)=>{const {limit,offset}=paging(r.query);const [rows]:any=await pool.query('SELECT * FROM reconciliation_runs WHERE tenant_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?',[r.auth.tenantId,limit,offset]);return response(r,rows);});
 app.get('/v1/reconciliation/exceptions',async(r:any)=>{const {limit,offset}=paging(r.query);const [rows]:any=await pool.query('SELECT * FROM reconciliation_exceptions WHERE tenant_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?',[r.auth.tenantId,limit,offset]);return response(r,rows);});
 app.post('/v1/reconciliation/runs',async(r:any,reply:any)=>{const v=z.object({provider:z.string().default('sandbox'),period_start:z.string(),period_end:z.string()}).parse(r.body);return reply.code(201).send(response(r,await financial.reconcile(r.auth.tenantId,v.provider,v.period_start,v.period_end)));});
 app.post('/v1/reconciliation/exceptions/:id/resolve',async(r:any)=>{const v=z.object({resolution:z.string().min(1)}).parse(r.body);const [x]:any=await pool.query("UPDATE reconciliation_exceptions SET status='RESOLVED',resolution=?,resolved_at=CURRENT_TIMESTAMP(6) WHERE id=? AND tenant_id=? AND status='OPEN'",[v.resolution,r.params.id,r.auth.tenantId]);if(!x.affectedRows)throw fail('RECONCILIATION_EXCEPTION_NOT_FOUND',404);return response(r,{id:r.params.id,status:'RESOLVED'});});

 app.post('/v1/compliance/identity/verify',async(r:any)=>{await requirePermission(r,'compliance.manage');const v=z.object({merchant_id:z.string().uuid(),document_id:z.string().optional(),person_id:z.string().optional(),country:z.string().length(2),return_url:z.string().url().optional()}).parse(r.body);return response(r,await compliance.verifyIdentity(r.auth.tenantId,v.merchant_id,v));});
 app.get('/v1/risk/assessments',async(r:any)=>{const {limit,offset}=paging(r.query);const [rows]:any=await pool.query('SELECT * FROM risk_assessments WHERE tenant_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?',[r.auth.tenantId,limit,offset]);return response(r,rows);});
 app.post('/v1/risk/assess',async(r:any)=>{const v=z.object({payment_attempt_id:z.string().uuid().optional(),payment_id:z.string().uuid().optional(),amount_minor:z.union([z.string(),z.number().int().positive()]),currency:z.string().length(3),customer_id:z.string().uuid().nullable().optional(),reference:z.string().optional()}).parse(r.body);return response(r,await risk.assess(r.auth.tenantId,{paymentAttemptId:v.payment_attempt_id,paymentId:v.payment_id,amountMinor:v.amount_minor,currency:v.currency,customerId:v.customer_id,reference:v.reference}));});

 app.get('/v1/disputes',async(r:any)=>{const {limit,offset}=paging(r.query);const [rows]:any=await pool.query('SELECT * FROM disputes WHERE tenant_id=? ORDER BY opened_at DESC LIMIT ? OFFSET ?',[r.auth.tenantId,limit,offset]);return response(r,rows);});
 app.get('/v1/disputes/:id',async(r:any)=>{const [d]:any=await pool.query('SELECT * FROM disputes WHERE id=? AND tenant_id=?',[r.params.id,r.auth.tenantId]);if(!d[0])throw fail('DISPUTE_NOT_FOUND',404);const [e]:any=await pool.query('SELECT * FROM dispute_evidence WHERE dispute_id=? AND tenant_id=? ORDER BY created_at DESC',[r.params.id,r.auth.tenantId]);const [events]:any=await pool.query('SELECT * FROM dispute_events WHERE dispute_id=? AND tenant_id=? ORDER BY created_at DESC',[r.params.id,r.auth.tenantId]);return response(r,{dispute:d[0],evidence:e,events});});
 app.post('/v1/disputes',async(r:any,reply:any)=>{const v=z.object({merchant_id:z.string().uuid(),payment_id:z.string().uuid(),amount_minor:z.union([z.string(),z.number().int().positive()]),currency:z.string().length(3),reason:z.string().max(128),response_due_at:z.string().datetime().optional()}).parse(r.body);const id=crypto.randomUUID();await pool.query('INSERT INTO disputes(id,tenant_id,merchant_id,payment_id,provider_dispute_id,amount_minor,currency,reason,status,response_due_at) VALUES(?,?,?,?,?,?,?,?,?,?)',[id,r.auth.tenantId,v.merchant_id,v.payment_id,null,v.amount_minor,v.currency,v.reason,'OPEN',v.response_due_at?new Date(v.response_due_at):null]);await pool.query('INSERT INTO dispute_events(id,tenant_id,dispute_id,event_type,payload_json) VALUES(?,?,?,?,?)',[crypto.randomUUID(),r.auth.tenantId,id,'dispute.opened',JSON.stringify(v)]);return reply.code(201).send(response(r,{id,status:'OPEN'}));});
 app.post('/v1/disputes/:id/evidence',async(r:any,reply:any)=>{const v=z.object({evidence_type:z.string().min(1),content:z.string().min(1)}).parse(r.body);const id=crypto.randomUUID();await pool.query('INSERT INTO dispute_evidence(id,tenant_id,dispute_id,evidence_type,content,status) VALUES(?,?,?,?,?,?)',[id,r.auth.tenantId,r.params.id,v.evidence_type,v.content,'DRAFT']);return reply.code(201).send(response(r,{id,status:'DRAFT'}));});
 app.post('/v1/disputes/:id/submit-evidence',async(r:any)=>{await pool.query("UPDATE dispute_evidence SET status='SUBMITTED',submitted_at=CURRENT_TIMESTAMP(6) WHERE dispute_id=? AND tenant_id=? AND status='DRAFT'",[r.params.id,r.auth.tenantId]);await pool.query('INSERT INTO dispute_events(id,tenant_id,dispute_id,event_type,payload_json) VALUES(?,?,?,?,?)',[crypto.randomUUID(),r.auth.tenantId,r.params.id,'evidence.submitted',JSON.stringify({})]);return response(r,{id:r.params.id,status:'SUBMITTED'});});

 app.get('/v1/kyc',async(r:any)=>{const merchantId=String((r.query as any)?.merchant_id||'');if(!merchantId)throw fail('MERCHANT_ID_REQUIRED',400);return response(r,await compliance.getOrCreate(r.auth.tenantId,merchantId));});
 app.post('/v1/kyc',async(r:any)=>{const v=z.object({merchant_id:z.string().uuid(),status:z.enum(['NOT_STARTED','IN_REVIEW','ACTION_REQUIRED','APPROVED','REJECTED']).optional(),business_name:z.string().optional(),business_type:z.string().optional(),country:z.string().length(2).optional(),registration_number:z.string().optional(),website:z.string().url().optional()}).parse(r.body);return response(r,await compliance.update(r.auth.tenantId,v.merchant_id,v));});
 app.get('/v1/bank-accounts',async(r:any)=>{const [rows]:any=await pool.query('SELECT id,merchant_id,provider,account_holder_name,country,currency,bank_name,account_last4,status,verified_at,created_at FROM bank_accounts WHERE tenant_id=? ORDER BY created_at DESC',[r.auth.tenantId]);return response(r,rows);});
 app.post('/v1/bank-accounts',async(r:any,reply:any)=>{const v=z.object({merchant_id:z.string().uuid(),account_holder_name:z.string(),country:z.string().length(2),currency:z.string().length(3),bank_name:z.string(),account_last4:z.string().length(4)}).parse(r.body);const id=crypto.randomUUID();await pool.query('INSERT INTO bank_accounts(id,tenant_id,merchant_id,provider,account_holder_name,country,currency,bank_name,account_last4,status,verified_at) VALUES(?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP(6))',[id,r.auth.tenantId,v.merchant_id,process.env.PAYMENT_PROVIDER||'sandbox',v.account_holder_name,v.country,v.currency.toUpperCase(),v.bank_name,v.account_last4,'PENDING']);return reply.code(201).send(response(r,{id,status:'PENDING',...v,verification:'provider_or_bank_verification_required'}));});

 app.get('/v1/products',async(r:any)=>{const [rows]:any=await pool.query('SELECT * FROM products WHERE tenant_id=? ORDER BY created_at DESC',[r.auth.tenantId]);return response(r,rows);});
 app.post('/v1/products',async(r:any,reply:any)=>{const v=z.object({merchant_id:z.string().uuid(),name:z.string().min(1),description:z.string().optional(),sku:z.string().optional(),type:z.enum(['ONE_TIME','SUBSCRIPTION']).optional(),active:z.boolean().optional(),metadata:z.object({}).passthrough().optional()}).parse(r.body);return reply.code(201).send(response(r,await billing.createProduct(r.auth.tenantId,v.merchant_id,{name:v.name,description:v.description,sku:v.sku,type:v.type,active:v.active,metadata:v.metadata})));});
 app.get('/v1/prices',async(r:any)=>{const [rows]:any=await pool.query('SELECT * FROM prices WHERE tenant_id=? ORDER BY created_at DESC',[r.auth.tenantId]);return response(r,rows);});
 app.post('/v1/prices',async(r:any,reply:any)=>{const v=z.object({product_id:z.string().uuid(),currency:z.string().length(3),unit_amount_minor:z.union([z.string(),z.number().int().positive()]),interval_unit:z.enum(['DAY','WEEK','MONTH','YEAR']).optional(),interval_count:z.number().int().positive().optional(),tax_behavior:z.enum(['INCLUSIVE','EXCLUSIVE']).optional(),metadata:z.object({}).passthrough().optional()}).parse(r.body);return reply.code(201).send(response(r,await billing.createPrice(r.auth.tenantId,v.product_id,{currency:v.currency.toUpperCase(),unit_amount_minor:String(v.unit_amount_minor),interval_unit:v.interval_unit,interval_count:v.interval_count,tax_behavior:v.tax_behavior,metadata:v.metadata})));});
 app.get('/v1/subscriptions',async(r:any)=>{const [rows]:any=await pool.query('SELECT * FROM subscriptions WHERE tenant_id=? ORDER BY created_at DESC',[r.auth.tenantId]);return response(r,rows);});
 app.post('/v1/subscriptions',async(r:any,reply:any)=>{const v=z.object({merchant_id:z.string().uuid(),customer_id:z.string().uuid(),price_id:z.string().uuid(),trial_days:z.number().int().min(0).optional(),status:z.enum(['TRIALING','ACTIVE','PAST_DUE','PAUSED','CANCELED','UNPAID','EXPIRED']).optional(),cancel_at_period_end:z.boolean().optional()}).parse(r.body);return reply.code(201).send(response(r,await billing.createSubscription(r.auth.tenantId,v.merchant_id,v.customer_id,v.price_id,{trial_days:v.trial_days,status:v.status,cancel_at_period_end:v.cancel_at_period_end})));});
 app.get('/v1/invoices',async(r:any)=>{const [rows]:any=await pool.query('SELECT * FROM invoices WHERE tenant_id=? ORDER BY created_at DESC',[r.auth.tenantId]);return response(r,rows);});

 app.get('/v1/reports/payments',async(r:any)=>{const rows=await reports.payments(r.auth.tenantId,(r.query as any)?.start,(r.query as any)?.end);return response(r,rows);});
 app.get('/v1/reports/refunds',async(r:any)=>{const rows=await reports.refunds(r.auth.tenantId,(r.query as any)?.start,(r.query as any)?.end);return response(r,rows);});
 app.post('/v1/report-exports',async(r:any,reply:any)=>{const v=z.object({report_type:z.enum(['payments','refunds']),format:z.enum(['CSV','JSON']).default('CSV'),start:z.string().optional(),end:z.string().optional()}).parse(r.body);const rows=v.report_type==='payments'?await reports.payments(r.auth.tenantId,v.start,v.end):await reports.refunds(r.auth.tenantId,v.start,v.end);const content=v.format==='JSON'?JSON.stringify(rows):rows.length?`${Object.keys(rows[0]).join(',')}\n${rows.map((x:any)=>Object.values(x).map(v=>JSON.stringify(v??'')).join(',')).join('\n')}`:'';const id=crypto.randomUUID();await pool.query('INSERT INTO report_exports(id,tenant_id,report_type,format,filters_json,status,content_text) VALUES(?,?,?,?,?,?,?)',[id,r.auth.tenantId,v.report_type,v.format,JSON.stringify({start:v.start,end:v.end}),'READY',content]);return reply.code(201).send(response(r,{id,format:v.format,content}));});
 app.get('/v1/report-exports',async(r:any)=>{const [rows]:any=await pool.query('SELECT id,report_type,format,status,created_at FROM report_exports WHERE tenant_id=? ORDER BY created_at DESC',[r.auth.tenantId]);return response(r,rows);});
 app.get('/v1/report-exports/:id',async(r:any)=>{const [rows]:any=await pool.query('SELECT * FROM report_exports WHERE id=? AND tenant_id=?',[r.params.id,r.auth.tenantId]);if(!rows[0])throw fail('REPORT_NOT_FOUND',404);return response(r,rows[0]);});

 app.get('/v1/payment-pages',async(r:any)=>{const [rows]:any=await pool.query('SELECT id,merchant_id,public_token,title,description,amount_minor,currency,status,expires_at,created_at FROM payment_pages WHERE tenant_id=? ORDER BY created_at DESC',[r.auth.tenantId]);return response(r,rows);});
 app.post('/v1/payment-pages',async(r:any,reply:any)=>{const v=z.object({merchant_id:z.string().uuid(),title:z.string().min(1),description:z.string().optional(),logo_url:z.string().url().optional(),amount_minor:z.union([z.string(),z.number().int().positive()]),currency:z.string().length(3),customer_fields:z.array(z.string()).default(['name','email']),payment_methods:z.array(z.string()).default(['CARD']),success_url:z.string().url().optional(),cancel_url:z.string().url().optional(),expires_at:z.string().datetime().optional()}).parse(r.body);const id=crypto.randomUUID(),token=crypto.randomBytes(24).toString('base64url');await pool.query('INSERT INTO payment_pages(id,tenant_id,merchant_id,public_token,title,description,logo_url,amount_minor,currency,customer_fields_json,payment_methods_json,success_url,cancel_url,expires_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,r.auth.tenantId,v.merchant_id,token,v.title,v.description||null,v.logo_url||null,v.amount_minor,v.currency.toUpperCase(),JSON.stringify(v.customer_fields),JSON.stringify(v.payment_methods),v.success_url||null,v.cancel_url||null,v.expires_at?new Date(v.expires_at):null]);return reply.code(201).send(response(r,{id,public_token:token,url:`/pay/${token}`,status:'ACTIVE'}));});
 app.get('/pay/:token',async(r:any)=>{const [rows]:any=await pool.query('SELECT * FROM payment_pages WHERE public_token=? AND status=\'ACTIVE\'',[r.params.token]);if(!rows[0])throw fail('PAYMENT_PAGE_NOT_FOUND',404);return response(r,rows[0]);});

 app.post('/v1/integrations/events/test',async(r:any)=>{await requirePermission(r,'settings.manage');const v=z.object({event_type:z.string().min(1),aggregate_type:z.string().min(1),aggregate_id:z.string().uuid(),payload:z.any(),idempotency_key:z.string().min(1)}).parse(r.body);const event_id=await emitOutbox(r.auth.tenantId,v.event_type,v.aggregate_type,v.aggregate_id,v.payload,v.idempotency_key);return response(r,{event_id,status:'PENDING'});});
 app.get('/v1/regional-policies',async(r:any)=>{const [rows]:any=await pool.query('SELECT * FROM regional_policies WHERE tenant_id=? ORDER BY country_code',[r.auth.tenantId]);return response(r,rows);});
 app.post('/v1/regional-policies',async(r:any)=>{await requirePermission(r,'settings.manage');const v=z.object({country:z.string().length(2),currency:z.string().length(3).optional(),taxRateBps:z.number().int().min(0).optional(),taxMode:z.string().optional(),invoiceRequired:z.boolean().optional(),eInvoicingMode:z.string().optional(),paymentProvider:z.string().optional(),payoutProvider:z.string().optional(),kycProvider:z.string().optional(),riskProvider:z.string().optional(),config:z.record(z.string(), z.any()).optional()}).parse(r.body);return response(r,await upsertRegionalPolicy(r.auth.tenantId,v.country,v));});
 app.get('/v1/regional-supported',async()=>supportedRegions);
 app.get('/v1/roles',async(r:any)=>{const [rows]:any=await pool.query('SELECT * FROM roles WHERE tenant_id=? OR tenant_id IS NULL ORDER BY name',[r.auth.tenantId]);return response(r,rows);});
 app.get('/v1/permissions',async(r:any)=>{const [rows]:any=await pool.query('SELECT * FROM permissions ORDER BY code');return response(r,rows);});
 app.post('/v1/roles',async(r:any,reply:any)=>{await requirePermission(r,'settings.manage');const v=z.object({name:z.string().min(1),description:z.string().optional(),permissions:z.array(z.string()).default([])}).parse(r.body);const id=crypto.randomUUID();await pool.query('INSERT INTO roles(id,tenant_id,name,description) VALUES(?,?,?,?)',[id,r.auth.tenantId,v.name,v.description||null]);for(const code of v.permissions){const [p]:any=await pool.query('SELECT id FROM permissions WHERE code=?',[code]);if(p[0])await pool.query('INSERT IGNORE INTO role_permissions(role_id,permission_id) VALUES(?,?)',[id,p[0].id]);}return reply.code(201).send(response(r,{id,name:v.name,permissions:v.permissions}));});
 app.get('/v1/users',async(r:any)=>{await requirePermission(r,'settings.manage');const [rows]:any=await pool.query('SELECT id,email,name,status,mfa_enabled,created_at FROM users WHERE tenant_id=? ORDER BY created_at DESC',[r.auth.tenantId]);return response(r,rows);});
 app.post('/v1/users',async(r:any,reply:any)=>{await requirePermission(r,'settings.manage');const v=z.object({email:z.string().email(),name:z.string().optional()}).parse(r.body);const id=crypto.randomUUID();await pool.query('INSERT INTO users(id,tenant_id,email,name,status) VALUES(?,?,?,?,?)',[id,r.auth.tenantId,v.email,v.name||null,'ACTIVE']);return reply.code(201).send(response(r,{id,...v,status:'ACTIVE'}));});
 app.post('/v1/users/:id/mfa/enable',async(r:any)=>{await requirePermission(r,'settings.manage');const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let secret='';const bytes=crypto.randomBytes(20);let b=0,bits=0;for(let i=0;i<bytes.length;){b=(b<<8)|bytes[i++];bits+=8;while(bits>=5){secret+=alphabet[(b>>>(bits-5))&31];bits-=5;}}if(bits>0)secret+=alphabet[(b<<(5-bits))&31];await pool.query('UPDATE users SET mfa_enabled=TRUE,mfa_secret_encrypted=? WHERE id=? AND tenant_id=?',[encryptProviderToken(secret),r.params.id,r.auth.tenantId]);const [u]:any=await pool.query('SELECT email FROM users WHERE id=? AND tenant_id=?',[r.params.id,r.auth.tenantId]);const label=encodeURIComponent(`PaymentPlatform:${u[0]?.email||r.params.id}`);return response(r,{id:r.params.id,mfa_enabled:true,otpauth_uri:`otpauth://totp/${label}?secret=${secret}&issuer=PaymentPlatform`});});

}
