import crypto from 'node:crypto';
import {pool} from '../db/mysql.js';
import {encryptProviderToken,decryptProviderToken} from '../../application/payments/token-vault.js';
const accountsBase=process.env.ZOHO_ACCOUNTS_URL||'https://accounts.zoho.com';
const booksBase=process.env.ZOHO_BOOKS_API_URL||'https://www.zohoapis.com/books/v3';
const clientId=process.env.ZOHO_BOOKS_CLIENT_ID||''; const clientSecret=process.env.ZOHO_BOOKS_CLIENT_SECRET||''; const redirectUri=process.env.ZOHO_BOOKS_REDIRECT_URI||'';
const scopes=process.env.ZOHO_BOOKS_SCOPES||'ZohoBooks.contacts.CREATE,ZohoBooks.contacts.READ,ZohoBooks.invoices.READ,ZohoBooks.customerpayments.CREATE,ZohoBooks.customerpayments.READ,ZohoBooks.settings.READ';
export class ZohoBooksService {
 authorizationUrl(state:string){if(!clientId||!redirectUri)throw Object.assign(new Error('ZOHO_BOOKS_OAUTH_NOT_CONFIGURED'),{code:'ZOHO_BOOKS_OAUTH_NOT_CONFIGURED',statusCode:503});const u=new URL(`${accountsBase}/oauth/v2/auth`);u.searchParams.set('client_id',clientId);u.searchParams.set('response_type','code');u.searchParams.set('scope',scopes);u.searchParams.set('redirect_uri',redirectUri);u.searchParams.set('access_type','offline');u.searchParams.set('prompt','consent');u.searchParams.set('state',state);return u.toString();}
 async exchangeCode(code:string,tenantId:string){const body=new URLSearchParams({grant_type:'authorization_code',client_id:clientId,client_secret:clientSecret,redirect_uri:redirectUri,code});const r=await fetch(`${accountsBase}/oauth/v2/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});const j:any=await r.json();if(!r.ok||j.error)throw Object.assign(new Error(j.error||'ZOHO_OAUTH_FAILED'),{code:'ZOHO_OAUTH_FAILED',statusCode:502});const orgResponse=await fetch(`${booksBase}/organizations`,{headers:{Authorization:`Zoho-oauthtoken ${j.access_token}`}});const orgJson:any=await orgResponse.json();const organizationId=String(j.organization_id||orgJson?.organizations?.[0]?.organization_id||'');if(!organizationId)throw Object.assign(new Error('ZOHO_ORGANIZATION_NOT_FOUND'),{code:'ZOHO_ORGANIZATION_NOT_FOUND',statusCode:502});const id=crypto.randomUUID();await pool.query(`INSERT INTO integration_connections(id,tenant_id,provider,status,external_account_id,access_token_encrypted,refresh_token_encrypted,access_token_expires_at,config_json) VALUES(?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE status='ACTIVE',external_account_id=VALUES(external_account_id),access_token_encrypted=VALUES(access_token_encrypted),refresh_token_encrypted=COALESCE(VALUES(refresh_token_encrypted),refresh_token_encrypted),access_token_expires_at=VALUES(access_token_expires_at),config_json=VALUES(config_json)`,[id,tenantId,'zoho_books','ACTIVE',organizationId,encryptProviderToken(String(j.access_token)),j.refresh_token?encryptProviderToken(String(j.refresh_token)):null,new Date(Date.now()+Number(j.expires_in||3600)*1000),JSON.stringify({api_domain:j.api_domain||'https://www.zohoapis.com'})]);return {connected:true,organization_id:organizationId};}
 private async connection(tenantId:string){const [rows]:any=await pool.query("SELECT * FROM integration_connections WHERE tenant_id=? AND provider='zoho_books' AND status='ACTIVE'",[tenantId]);if(!rows[0])throw Object.assign(new Error('ZOHO_BOOKS_NOT_CONNECTED'),{code:'ZOHO_BOOKS_NOT_CONNECTED',statusCode:409});return rows[0];}
 private async accessToken(tenantId:string){const c=await this.connection(tenantId);if(c.access_token_expires_at&&new Date(c.access_token_expires_at).getTime()>Date.now()+60000)return {token:decryptProviderToken(c.access_token_encrypted),org:c.external_account_id};const refresh=decryptProviderToken(c.refresh_token_encrypted);const body=new URLSearchParams({grant_type:'refresh_token',client_id:clientId,client_secret:clientSecret,refresh_token:refresh});const r=await fetch(`${accountsBase}/oauth/v2/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});const j:any=await r.json();if(!r.ok||!j.access_token)throw Object.assign(new Error(j.error||'ZOHO_TOKEN_REFRESH_FAILED'),{code:'ZOHO_TOKEN_REFRESH_FAILED',statusCode:502});await pool.query('UPDATE integration_connections SET access_token_encrypted=?,access_token_expires_at=? WHERE id=?',[encryptProviderToken(j.access_token),new Date(Date.now()+Number(j.expires_in||3600)*1000),c.id]);return {token:j.access_token,org:c.external_account_id};}
 private async call(tenantId:string,path:string,method='GET',body?:any){const {token,org}=await this.accessToken(tenantId);const u=new URL(`${booksBase}${path}`);u.searchParams.set('organization_id',org);const r=await fetch(u,{method,headers:{Authorization:`Zoho-oauthtoken ${token}`,'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const text=await r.text();let j:any={};try{j=JSON.parse(text)}catch{}if(!r.ok||j.code&&j.code!==0)throw Object.assign(new Error(j.message||`ZOHO_HTTP_${r.status}`),{code:'ZOHO_BOOKS_API_ERROR',statusCode:502});return j;}
 listInvoices(tenantId:string,params=''){return this.call(tenantId,`/invoices${params?`?${params}`:''}`);}
 getInvoice(tenantId:string,id:string){return this.call(tenantId,`/invoices/${encodeURIComponent(id)}`);}
 createCustomerPayment(tenantId:string,input:any){return this.call(tenantId,'/customerpayments','POST',input);}
 createContact(tenantId:string,input:any){return this.call(tenantId,'/contacts','POST',input);}
 status(tenantId:string){return this.connection(tenantId).then(c=>({provider:'zoho_books',status:c.status,organization_id:c.external_account_id,updated_at:c.updated_at}));}
}
