CREATE TABLE IF NOT EXISTS error_reports (
 id CHAR(36) PRIMARY KEY,
 tenant_id CHAR(36) NULL,
 user_id CHAR(36) NULL,
 request_id VARCHAR(128) NOT NULL,
 method VARCHAR(16) NOT NULL,
 route VARCHAR(512) NOT NULL,
 status_code INT NOT NULL,
 error_code VARCHAR(128) NOT NULL,
 message TEXT NOT NULL,
 ip VARCHAR(64),
 user_agent TEXT,
 query_json JSON NULL,
 params_json JSON NULL,
 body_json JSON NULL,
 headers_json JSON NULL,
 stack TEXT NULL,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 INDEX(tenant_id,created_at),
 INDEX(request_id),
 INDEX(error_code),
 INDEX(status_code),
 INDEX(created_at)
);
